name: test
on : [workflow_dispatch]

jobs:
  blah:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo $env:PATH
          ${{github.workspace}}/ex01_Simple_Int_Param.exe
          echo $LASTEXITCODE
