name: test
on : [workflow_dispatch]

jobs:
  blah:
    runs-on: windows-2022
    steps:
      - run: |
          cat C:\mingw64\build-info.txt
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test
          path: C:\mingw64
          retention-days: 1
        
